"""empty message

Revision ID: 01b84e632f8c
Revises: 471e3af2156c
Create Date: 2020-06-27 19:08:55.891595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01b84e632f8c'
down_revision = '471e3af2156c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_product_category_feature', sa.Column('feature_required', sa.Boolean(), nullable=True))
    op.drop_column('global_product_category_feature', 'required_features')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_product_category_feature', sa.Column('required_features', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('global_product_category_feature', 'feature_required')
    # ### end Alembic commands ###
