"""empty message

Revision ID: 0a6318f4393b
Revises: cfd6db82cb92
Create Date: 2020-06-20 10:05:45.025113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6318f4393b'
down_revision = 'cfd6db82cb92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_product_features_units', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_product_features_units', 'order')
    # ### end Alembic commands ###
