"""empty message

Revision ID: 23d3ab2f61f2
Revises: d22de9bece7d
Create Date: 2020-07-14 20:24:08.721963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d3ab2f61f2'
down_revision = 'd22de9bece7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_product_products_varient', sa.Column('product_approve', sa.Boolean(), nullable=True))
    op.add_column('global_product_products_varient', sa.Column('product_live', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_product_products_varient', 'product_live')
    op.drop_column('global_product_products_varient', 'product_approve')
    # ### end Alembic commands ###
