"""empty message

Revision ID: 2d89ad83057f
Revises: 68448429ce74
Create Date: 2020-06-26 18:01:08.342447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d89ad83057f'
down_revision = '68448429ce74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_product_products_varient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['global_product_category.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['global_product_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_product_varient_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.Column('product_varient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['global_product_category_feature.id'], ),
    sa.ForeignKeyConstraint(['product_varient_id'], ['global_product_products_varient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('global_product_varient')
    op.add_column('global_product_features_boolean', sa.Column('product_varient_id', sa.Integer(), nullable=True))
    op.drop_constraint('global_product_features_boolean_ibfk_2', 'global_product_features_boolean', type_='foreignkey')
    op.create_foreign_key(None, 'global_product_features_boolean', 'global_product_products_varient', ['product_varient_id'], ['id'])
    op.drop_column('global_product_features_boolean', 'product_id')
    op.add_column('global_product_features_date', sa.Column('product_varient_id', sa.Integer(), nullable=True))
    op.drop_constraint('global_product_features_date_ibfk_2', 'global_product_features_date', type_='foreignkey')
    op.create_foreign_key(None, 'global_product_features_date', 'global_product_products_varient', ['product_varient_id'], ['id'])
    op.drop_column('global_product_features_date', 'product_id')
    op.add_column('global_product_features_double', sa.Column('product_varient_id', sa.Integer(), nullable=True))
    op.drop_constraint('global_product_features_double_ibfk_2', 'global_product_features_double', type_='foreignkey')
    op.create_foreign_key(None, 'global_product_features_double', 'global_product_products_varient', ['product_varient_id'], ['id'])
    op.drop_column('global_product_features_double', 'product_id')
    op.add_column('global_product_features_extra', sa.Column('product_varient_id', sa.Integer(), nullable=True))
    op.drop_constraint('global_product_features_extra_ibfk_1', 'global_product_features_extra', type_='foreignkey')
    op.create_foreign_key(None, 'global_product_features_extra', 'global_product_products_varient', ['product_varient_id'], ['id'])
    op.drop_column('global_product_features_extra', 'product_id')
    op.add_column('global_product_features_integer', sa.Column('product_varient_id', sa.Integer(), nullable=True))
    op.drop_constraint('global_product_features_integer_ibfk_2', 'global_product_features_integer', type_='foreignkey')
    op.create_foreign_key(None, 'global_product_features_integer', 'global_product_products_varient', ['product_varient_id'], ['id'])
    op.drop_column('global_product_features_integer', 'product_id')
    op.add_column('global_product_features_recommended', sa.Column('product_varient_id', sa.Integer(), nullable=True))
    op.drop_constraint('global_product_features_recommended_ibfk_4', 'global_product_features_recommended', type_='foreignkey')
    op.create_foreign_key(None, 'global_product_features_recommended', 'global_product_products_varient', ['product_varient_id'], ['id'])
    op.drop_column('global_product_features_recommended', 'product_id')
    op.add_column('global_product_features_string', sa.Column('product_varient_id', sa.Integer(), nullable=True))
    op.drop_constraint('global_product_features_string_ibfk_2', 'global_product_features_string', type_='foreignkey')
    op.create_foreign_key(None, 'global_product_features_string', 'global_product_products_varient', ['product_varient_id'], ['id'])
    op.drop_column('global_product_features_string', 'product_id')
    op.add_column('global_product_products', sa.Column('varient', sa.Boolean(), nullable=True))
    op.drop_constraint('global_product_products_ibfk_1', 'global_product_products', type_='foreignkey')
    op.drop_column('global_product_products', 'category_id')
    op.drop_column('global_product_products', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_product_products', sa.Column('name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('global_product_products', sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('global_product_products_ibfk_1', 'global_product_products', 'global_product_category', ['category_id'], ['id'])
    op.drop_column('global_product_products', 'varient')
    op.add_column('global_product_features_string', sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'global_product_features_string', type_='foreignkey')
    op.create_foreign_key('global_product_features_string_ibfk_2', 'global_product_features_string', 'global_product_products', ['product_id'], ['id'])
    op.drop_column('global_product_features_string', 'product_varient_id')
    op.add_column('global_product_features_recommended', sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'global_product_features_recommended', type_='foreignkey')
    op.create_foreign_key('global_product_features_recommended_ibfk_4', 'global_product_features_recommended', 'global_product_products', ['product_id'], ['id'])
    op.drop_column('global_product_features_recommended', 'product_varient_id')
    op.add_column('global_product_features_integer', sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'global_product_features_integer', type_='foreignkey')
    op.create_foreign_key('global_product_features_integer_ibfk_2', 'global_product_features_integer', 'global_product_products', ['product_id'], ['id'])
    op.drop_column('global_product_features_integer', 'product_varient_id')
    op.add_column('global_product_features_extra', sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'global_product_features_extra', type_='foreignkey')
    op.create_foreign_key('global_product_features_extra_ibfk_1', 'global_product_features_extra', 'global_product_products', ['product_id'], ['id'])
    op.drop_column('global_product_features_extra', 'product_varient_id')
    op.add_column('global_product_features_double', sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'global_product_features_double', type_='foreignkey')
    op.create_foreign_key('global_product_features_double_ibfk_2', 'global_product_features_double', 'global_product_products', ['product_id'], ['id'])
    op.drop_column('global_product_features_double', 'product_varient_id')
    op.add_column('global_product_features_date', sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'global_product_features_date', type_='foreignkey')
    op.create_foreign_key('global_product_features_date_ibfk_2', 'global_product_features_date', 'global_product_products', ['product_id'], ['id'])
    op.drop_column('global_product_features_date', 'product_varient_id')
    op.add_column('global_product_features_boolean', sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'global_product_features_boolean', type_='foreignkey')
    op.create_foreign_key('global_product_features_boolean_ibfk_2', 'global_product_features_boolean', 'global_product_products', ['product_id'], ['id'])
    op.drop_column('global_product_features_boolean', 'product_varient_id')
    op.create_table('global_product_varient',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_feature_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_feature_id'], ['global_product_category_feature.id'], name='global_product_varient_ibfk_1'),
    sa.ForeignKeyConstraint(['product_id'], ['global_product_products.id'], name='global_product_varient_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('global_product_varient_features')
    op.drop_table('global_product_products_varient')
    # ### end Alembic commands ###
