"""empty message

Revision ID: 46dcc42afbd5
Revises: 1c1220c16b41
Create Date: 2020-07-03 12:52:53.351148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46dcc42afbd5'
down_revision = '1c1220c16b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_product_category_feature', sa.Column('filterable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_product_category_feature', 'filterable')
    # ### end Alembic commands ###
