"""empty message

Revision ID: 471e3af2156c
Revises: 2d89ad83057f
Create Date: 2020-06-27 13:17:56.073101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '471e3af2156c'
down_revision = '2d89ad83057f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_product_varient_features', sa.Column('product_id', sa.Integer(), nullable=True))
    op.drop_constraint('global_product_varient_features_ibfk_2', 'global_product_varient_features', type_='foreignkey')
    op.create_foreign_key(None, 'global_product_varient_features', 'global_product_products', ['product_id'], ['id'])
    op.drop_column('global_product_varient_features', 'product_varient_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_product_varient_features', sa.Column('product_varient_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'global_product_varient_features', type_='foreignkey')
    op.create_foreign_key('global_product_varient_features_ibfk_2', 'global_product_varient_features', 'global_product_products_varient', ['product_varient_id'], ['id'])
    op.drop_column('global_product_varient_features', 'product_id')
    # ### end Alembic commands ###
