"""empty message

Revision ID: 53c79c9792b0
Revises: f78892e6f49b
Create Date: 2020-06-16 19:20:48.695382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53c79c9792b0'
down_revision = 'f78892e6f49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_product_features_units_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_product_features_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('units_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['units_id'], ['global_product_features_units_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('global_product_category_feature', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'global_product_category_feature', 'global_product_features_units', ['unit_id'], ['id'])
    op.drop_column('global_product_category_feature', 'unit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_product_category_feature', sa.Column('unit', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'global_product_category_feature', type_='foreignkey')
    op.drop_column('global_product_category_feature', 'unit_id')
    op.drop_table('global_product_features_units')
    op.drop_table('global_product_features_units_types')
    # ### end Alembic commands ###
