"""empty message

Revision ID: 68448429ce74
Revises: cfb890094ea4
Create Date: 2020-06-23 16:27:46.087258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68448429ce74'
down_revision = 'cfb890094ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_product_category_feature', sa.Column('required_features', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_product_category_feature', 'required_features')
    # ### end Alembic commands ###
