"""empty message

Revision ID: 920be84ff4e2
Revises: 4e5345675df4
Create Date: 2020-07-15 13:19:59.103612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920be84ff4e2'
down_revision = '4e5345675df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('fips_code', sa.String(length=200), nullable=True),
    sa.Column('iso2', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('flag', sa.Boolean(), nullable=True),
    sa.Column('wikiDataId', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('states')
    # ### end Alembic commands ###
