"""empty message

Revision ID: b21379578f57
Revises: cd87fcd5d755
Create Date: 2020-07-16 15:17:46.038338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b21379578f57'
down_revision = 'cd87fcd5d755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('cities_test_ibfk_1', table_name='cities')
    op.drop_index('cities_test_ibfk_2', table_name='cities')
    op.drop_column('cities', 'updated_on')
    op.alter_column('countries', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
    op.alter_column('countries', 'flag',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('countries', 'name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.alter_column('countries', 'wikiDataId',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='Rapid API GeoDB Cities',
               existing_nullable=True)
    op.add_column('global_product_products_varient', sa.Column('country_of_origin1', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'global_product_products_varient', 'countries', ['country_of_origin1'], ['id'])
    op.drop_column('global_product_products_varient', 'country_of_origin')
    op.alter_column('states', 'country_code',
               existing_type=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=2),
               nullable=True)
    op.alter_column('states', 'country_id',
               existing_type=mysql.MEDIUMINT(unsigned=True),
               nullable=True)
    op.alter_column('states', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
    op.alter_column('states', 'flag',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('states', 'name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.alter_column('states', 'wikiDataId',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='Rapid API GeoDB Cities',
               existing_nullable=True)
    op.drop_index('country_region', table_name='states')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('country_region', 'states', ['country_id'], unique=False)
    op.alter_column('states', 'wikiDataId',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               comment='Rapid API GeoDB Cities',
               existing_nullable=True)
    op.alter_column('states', 'name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.alter_column('states', 'flag',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('states', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('states', 'country_id',
               existing_type=mysql.MEDIUMINT(unsigned=True),
               nullable=False)
    op.alter_column('states', 'country_code',
               existing_type=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=2),
               nullable=False)
    op.add_column('global_product_products_varient', sa.Column('country_of_origin', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'global_product_products_varient', type_='foreignkey')
    op.drop_column('global_product_products_varient', 'country_of_origin1')
    op.alter_column('countries', 'wikiDataId',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               comment='Rapid API GeoDB Cities',
               existing_nullable=True)
    op.alter_column('countries', 'name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.alter_column('countries', 'flag',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('countries', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    op.add_column('cities', sa.Column('updated_on', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.create_index('cities_test_ibfk_2', 'cities', ['country_id'], unique=False)
    op.create_index('cities_test_ibfk_1', 'cities', ['state_id'], unique=False)
    # ### end Alembic commands ###
