"""empty message

Revision ID: cfd6db82cb92
Revises: f479f99ebb95
Create Date: 2020-06-19 17:32:52.547140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cfd6db82cb92'
down_revision = 'f479f99ebb95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_product_features_recommended', sa.Column('feature_id', sa.Integer(), nullable=True))
    op.drop_constraint('global_product_features_recommended_ibfk_1', 'global_product_features_recommended', type_='foreignkey')
    op.create_foreign_key(None, 'global_product_features_recommended', 'global_product_category_feature', ['feature_id'], ['id'])
    op.drop_column('global_product_features_recommended', 'category_feature_global_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_product_features_recommended', sa.Column('category_feature_global_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'global_product_features_recommended', type_='foreignkey')
    op.create_foreign_key('global_product_features_recommended_ibfk_1', 'global_product_features_recommended', 'global_product_category_feature', ['category_feature_global_id'], ['id'])
    op.drop_column('global_product_features_recommended', 'feature_id')
    # ### end Alembic commands ###
