"""empty message

Revision ID: d22de9bece7d
Revises: f2454ac7d79d
Create Date: 2020-07-14 13:31:20.399204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22de9bece7d'
down_revision = 'f2454ac7d79d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_product_products_varient', sa.Column('country_of_origin', sa.String(length=100), nullable=True))
    op.add_column('global_product_products_varient', sa.Column('description_of_products', sa.String(length=2000), nullable=True))
    op.add_column('global_product_products_varient', sa.Column('is_product_features_added', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_product_products_varient', 'is_product_features_added')
    op.drop_column('global_product_products_varient', 'description_of_products')
    op.drop_column('global_product_products_varient', 'country_of_origin')
    # ### end Alembic commands ###
