"""empty message

Revision ID: d8dda37677dc
Revises: ddc5a489ce24
Create Date: 2020-06-28 11:42:05.838052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8dda37677dc'
down_revision = 'ddc5a489ce24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_product_features_units', sa.Column('exp', sa.String(length=5), nullable=True))
    op.add_column('global_product_features_units', sa.Column('value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_product_features_units', 'value')
    op.drop_column('global_product_features_units', 'exp')
    # ### end Alembic commands ###
