"""empty message

Revision ID: fdd71b797e32
Revises: d8dda37677dc
Create Date: 2020-06-28 19:01:00.684342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd71b797e32'
down_revision = 'd8dda37677dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_product_features_units', sa.Column('selected_unit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_product_features_units', 'selected_unit')
    # ### end Alembic commands ###
