"""empty message

Revision ID: 57afd5871c1e
Revises: 1aab2d557ae8
Create Date: 2020-06-06 19:05:03.836919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57afd5871c1e'
down_revision = '1aab2d557ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('primary_phone_no', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    # ### end Alembic commands ###
