"""empty message

Revision ID: 81ef91b21fe6
Revises: 2b269549ba82
Create Date: 2020-06-13 14:09:38.864359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ef91b21fe6'
down_revision = '2b269549ba82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('address_ibfk_1', 'address', type_='foreignkey')
    op.create_foreign_key(None, 'address', 'employee', ['employee_id1'], ['employee_id'])
    op.drop_constraint('department_ibfk_1', 'department', type_='foreignkey')
    op.create_foreign_key(None, 'department', 'employee', ['employee_id1'], ['employee_id'])
    op.drop_constraint('designation_ibfk_1', 'designation', type_='foreignkey')
    op.create_foreign_key(None, 'designation', 'employee', ['employee_id1'], ['employee_id'])
    op.drop_constraint('employee_personal_detail_ibfk_1', 'employee_personal_detail', type_='foreignkey')
    op.create_foreign_key(None, 'employee_personal_detail', 'employee', ['employee_id1'], ['employee_id'])
    op.add_column('features__groups__global', sa.Column('sub_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'features__groups__global', 'category__global', ['sub_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'features__groups__global', type_='foreignkey')
    op.drop_column('features__groups__global', 'sub_category_id')
    op.drop_constraint(None, 'employee_personal_detail', type_='foreignkey')
    op.create_foreign_key('employee_personal_detail_ibfk_1', 'employee_personal_detail', 'employee', ['employee_id1'], ['id'])
    op.drop_constraint(None, 'designation', type_='foreignkey')
    op.create_foreign_key('designation_ibfk_1', 'designation', 'employee', ['employee_id1'], ['id'])
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.create_foreign_key('department_ibfk_1', 'department', 'employee', ['employee_id1'], ['id'])
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.create_foreign_key('address_ibfk_1', 'address', 'employee', ['employee_id1'], ['id'])
    # ### end Alembic commands ###
