"""empty message

Revision ID: 00be511a3713
Revises: b0ca1007ed6e
Create Date: 2020-08-02 17:08:08.488156

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00be511a3713'
down_revision = 'b0ca1007ed6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.drop_constraint('address_ibfk_1', 'address', type_='foreignkey')
    op.create_foreign_key(None, 'address', 'employee', ['employee_id'], ['employee_id'])
    op.drop_column('address', 'employee_id1')
    op.add_column('department', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.drop_constraint('department_ibfk_1', 'department', type_='foreignkey')
    op.create_foreign_key(None, 'department', 'employee', ['employee_id'], ['employee_id'])
    op.drop_column('department', 'employee_id1')
    op.add_column('designation', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.drop_constraint('designation_ibfk_1', 'designation', type_='foreignkey')
    op.create_foreign_key(None, 'designation', 'employee', ['employee_id'], ['employee_id'])
    op.drop_column('designation', 'employee_id1')
    op.add_column('employee_personal_detail', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.drop_constraint('employee_personal_detail_ibfk_1', 'employee_personal_detail', type_='foreignkey')
    op.create_foreign_key(None, 'employee_personal_detail', 'employee', ['employee_id'], ['employee_id'])
    op.drop_column('employee_personal_detail', 'employee_id1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_personal_detail', sa.Column('employee_id1', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employee_personal_detail', type_='foreignkey')
    op.create_foreign_key('employee_personal_detail_ibfk_1', 'employee_personal_detail', 'employee', ['employee_id1'], ['employee_id'])
    op.drop_column('employee_personal_detail', 'employee_id')
    op.add_column('designation', sa.Column('employee_id1', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'designation', type_='foreignkey')
    op.create_foreign_key('designation_ibfk_1', 'designation', 'employee', ['employee_id1'], ['employee_id'])
    op.drop_column('designation', 'employee_id')
    op.add_column('department', sa.Column('employee_id1', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.create_foreign_key('department_ibfk_1', 'department', 'employee', ['employee_id1'], ['employee_id'])
    op.drop_column('department', 'employee_id')
    op.add_column('address', sa.Column('employee_id1', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.create_foreign_key('address_ibfk_1', 'address', 'employee', ['employee_id1'], ['employee_id'])
    op.drop_column('address', 'employee_id')
    # ### end Alembic commands ###
