"""empty message

Revision ID: 00cfff86a521
Revises: 92bdbdb9bcbf
Create Date: 2020-09-18 01:36:31.494670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00cfff86a521'
down_revision = '92bdbdb9bcbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('address_line_1', sa.String(length=100), nullable=True),
    sa.Column('address_line_2', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=30), nullable=True),
    sa.Column('city_town', sa.String(length=30), nullable=True),
    sa.Column('landmark', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company_company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('legal_name', sa.String(length=100), nullable=True),
    sa.Column('gstin_no', sa.String(length=100), nullable=True),
    sa.Column('cin_no', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('phone_no', sa.String(length=20), nullable=True),
    sa.Column('fax', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company_company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('employee', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employee', 'company_company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'company_id')
    op.drop_table('company_info')
    op.drop_table('company_address')
    # ### end Alembic commands ###
