"""empty message

Revision ID: 3001d192373e
Revises: 44a05a850897
Create Date: 2020-08-02 01:33:20.651880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3001d192373e'
down_revision = '44a05a850897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_product_category_feature', sa.Column('unit_types_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'global_product_category_feature', 'general_data_units_types', ['unit_types_id'], ['id'])
    op.drop_column('global_product_category_feature', 'unit_types_id1')
    op.drop_column('global_product_category_feature', 'features_datatype_id')
    op.drop_column('global_product_category_feature', 'unit_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_product_category_feature', sa.Column('unit_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('global_product_category_feature', sa.Column('features_datatype_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('global_product_category_feature', sa.Column('unit_types_id1', mysql.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'global_product_category_feature', type_='foreignkey')
    op.drop_column('global_product_category_feature', 'unit_types_id')
    # ### end Alembic commands ###
