"""empty message

Revision ID: 44a05a850897
Revises: 9cb50b78b17e
Create Date: 2020-08-01 23:56:12.457175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a05a850897'
down_revision = '9cb50b78b17e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_data_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('units_type_id', sa.Integer(), nullable=True),
    sa.Column('exp', sa.String(length=5), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['units_type_id'], ['general_data_units_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('general_data_units')
    # ### end Alembic commands ###
