"""empty message

Revision ID: 4e5345675df4
Revises: 23d3ab2f61f2
Create Date: 2020-07-15 12:54:08.472599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e5345675df4'
down_revision = '23d3ab2f61f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('iso3', sa.String(length=5), nullable=True),
    sa.Column('iso2', sa.String(length=5), nullable=True),
    sa.Column('phonecode', sa.String(length=200), nullable=True),
    sa.Column('capital', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=200), nullable=True),
    sa.Column('native', sa.String(length=200), nullable=True),
    sa.Column('emoji', sa.String(length=200), nullable=True),
    sa.Column('emojiU', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('flag', sa.Boolean(), nullable=True),
    sa.Column('wikiDataId', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries')
    # ### end Alembic commands ###
