"""empty message

Revision ID: 58efac41c066
Revises: 002b2491d301
Create Date: 2020-07-16 18:51:29.087952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58efac41c066'
down_revision = '002b2491d301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'global_product_products_varient', 'countries', ['country_of_origin'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'global_product_products_varient', type_='foreignkey')
    # ### end Alembic commands ###
