"""empty message

Revision ID: 608789dae0ce
Revises: 3001d192373e
Create Date: 2020-08-02 01:34:42.333636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608789dae0ce'
down_revision = '3001d192373e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_data_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('units_type_id', sa.Integer(), nullable=True),
    sa.Column('exp', sa.String(length=5), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['units_type_id'], ['general_data_units_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('global_product_category_feature', sa.Column('features_datatype_id', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'global_product_category_feature', 'general_data_datatype', ['features_datatype_id'], ['abbreviation'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'global_product_category_feature', type_='foreignkey')
    op.drop_column('global_product_category_feature', 'features_datatype_id')
    op.drop_table('general_data_units')
    # ### end Alembic commands ###
