"""empty message

Revision ID: 66b2f256c5cb
Revises: f0e32e04aafc
Create Date: 2020-09-30 01:50:41.375514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66b2f256c5cb'
down_revision = 'f0e32e04aafc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_users')
    op.add_column('company_role_user', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'company_role_user', 'company_company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company_role_user', type_='foreignkey')
    op.drop_column('company_role_user', 'company_id')
    op.create_table('company_users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company_company.id'], name='company_users_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user_user.id'], name='company_users_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
