"""empty message

Revision ID: 800588b24ccb
Revises: cdb17291bec9
Create Date: 2020-07-16 16:24:07.788422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '800588b24ccb'
down_revision = 'cdb17291bec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_product_varient_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['global_product_category_feature.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['global_product_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('global_product_features_extra')
    op.drop_table('global_product_features_double')
    op.drop_table('global_product_features_date')
    op.drop_table('global_product_features_integer_recommended')
    op.drop_table('global_product_features_integer')
    op.drop_table('global_product_features_double_recommended')
    op.drop_table('global_product_features_boolean')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_product_features_boolean',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feature_value', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('feature_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_varient_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`feature_value` in (0,1))', name='global_product_features_boolean_chk_1'),
    sa.ForeignKeyConstraint(['feature_id'], ['global_product_category_feature.id'], name='global_product_features_boolean_ibfk_1'),
    sa.ForeignKeyConstraint(['product_varient_id'], ['global_product_products_varient.id'], name='global_product_features_boolean_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('global_product_features_double_recommended',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feature_value', mysql.FLOAT(), nullable=True),
    sa.Column('feature_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['global_product_category_feature.id'], name='global_product_features_double_recommended_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('global_product_features_integer',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feature_value', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feature_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_varient_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['global_product_category_feature.id'], name='global_product_features_integer_ibfk_1'),
    sa.ForeignKeyConstraint(['product_varient_id'], ['global_product_products_varient.id'], name='global_product_features_integer_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('global_product_features_integer_recommended',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feature_value', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feature_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['global_product_category_feature.id'], name='global_product_features_integer_recommended_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('global_product_features_date',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feature_value', mysql.DATETIME(), nullable=True),
    sa.Column('feature_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_varient_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['global_product_category_feature.id'], name='global_product_features_date_ibfk_1'),
    sa.ForeignKeyConstraint(['product_varient_id'], ['global_product_products_varient.id'], name='global_product_features_date_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('global_product_features_double',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feature_value', mysql.FLOAT(), nullable=True),
    sa.Column('feature_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_varient_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['global_product_category_feature.id'], name='global_product_features_double_ibfk_1'),
    sa.ForeignKeyConstraint(['product_varient_id'], ['global_product_products_varient.id'], name='global_product_features_double_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('global_product_features_extra',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('product_varient_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feature_type_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('units', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_varient_id'], ['global_product_products_varient.id'], name='global_product_features_extra_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('global_product_varient_features')
    # ### end Alembic commands ###
