"""empty message

Revision ID: 92bdbdb9bcbf
Revises: c75a174e6cca
Create Date: 2020-09-12 20:59:11.456857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92bdbdb9bcbf'
down_revision = 'c75a174e6cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_company', sa.Column('create_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'company_company', 'user_user', ['create_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company_company', type_='foreignkey')
    op.drop_column('company_company', 'create_user_id')
    # ### end Alembic commands ###
