"""empty message

Revision ID: 9ca77cdb74cf
Revises: 8bc6d8b6ee45
Create Date: 2020-06-15 14:08:11.719926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca77cdb74cf'
down_revision = '8bc6d8b6ee45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('double__features__recommended__global',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_value', sa.Float(), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['category__feature__global.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integer__features__recommended__global',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_value', sa.Integer(), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['category__feature__global.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('string__features__recommended__global',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_value', sa.String(length=1000), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['category__feature__global.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommended__features__global',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_feature_global_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('string_seleted_id', sa.Integer(), nullable=True),
    sa.Column('integer_seleted_id', sa.Integer(), nullable=True),
    sa.Column('double_seleted_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_feature_global_id'], ['category__feature__global.id'], ),
    sa.ForeignKeyConstraint(['double_seleted_id'], ['double__features__recommended__global.id'], ),
    sa.ForeignKeyConstraint(['integer_seleted_id'], ['integer__features__recommended__global.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products__global.id'], ),
    sa.ForeignKeyConstraint(['string_seleted_id'], ['string__features__recommended__global.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('category__feature__global', sa.Column('recommendation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category__feature__global', 'recommendation')
    op.drop_table('recommended__features__global')
    op.drop_table('string__features__recommended__global')
    op.drop_table('integer__features__recommended__global')
    op.drop_table('double__features__recommended__global')
    # ### end Alembic commands ###
