"""empty message

Revision ID: 9fcfb7748037
Revises: 00cfff86a521
Create Date: 2020-09-20 03:10:25.932883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fcfb7748037'
down_revision = '00cfff86a521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_address', sa.Column('pin_code', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_address', 'pin_code')
    # ### end Alembic commands ###
