"""empty message

Revision ID: c1b8d7b6582f
Revises: 608789dae0ce
Create Date: 2020-08-02 01:40:12.440014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1b8d7b6582f'
down_revision = '608789dae0ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_product_features_datatype')
    op.drop_constraint('global_product_features_units_ibfk_1', 'global_product_features_units', type_='foreignkey')
    op.drop_column('global_product_features_units', 'units_type_id')
    op.drop_constraint('global_product_features_units_types_ibfk_1', 'global_product_features_units_types', type_='foreignkey')
    op.drop_column('global_product_features_units_types', 'selected_unit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_product_features_units_types', sa.Column('selected_unit', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('global_product_features_units_types_ibfk_1', 'global_product_features_units_types', 'global_product_features_units', ['selected_unit'], ['id'])
    op.add_column('global_product_features_units', sa.Column('units_type_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('global_product_features_units_ibfk_1', 'global_product_features_units', 'global_product_features_units_types', ['units_type_id'], ['id'])
    op.create_table('global_product_features_datatype',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
