"""empty message

Revision ID: c40d1d567e50
Revises: 5ae41e98f5c4
Create Date: 2020-09-26 19:44:13.358252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40d1d567e50'
down_revision = '5ae41e98f5c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'company_company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'company_id')
    # ### end Alembic commands ###
