"""empty message

Revision ID: cdb17291bec9
Revises: 78ba2cd193e0
Create Date: 2020-07-16 16:19:52.920263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb17291bec9'
down_revision = '78ba2cd193e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_product_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('varient', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_product_products_varient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('description_of_products', sa.String(length=2000), nullable=True),
    sa.Column('is_product_features_added', sa.Boolean(), nullable=True),
    sa.Column('product_live', sa.Boolean(), nullable=True),
    sa.Column('product_approve', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['global_product_category.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['global_product_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_product_products_varient')
    op.drop_table('global_product_products')
    # ### end Alembic commands ###
