"""empty message

Revision ID: ddc5a489ce24
Revises: 01b84e632f8c
Create Date: 2020-06-28 11:23:09.978194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc5a489ce24'
down_revision = '01b84e632f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_product_features_groups', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_product_features_groups', 'order')
    # ### end Alembic commands ###
