"""empty message

Revision ID: f0e32e04aafc
Revises: 7548e50e48bc
Create Date: 2020-09-29 02:12:33.388468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0e32e04aafc'
down_revision = '7548e50e48bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('address_line', sa.String(length=50), nullable=True))
    op.drop_column('address', 'address_line2')
    op.drop_column('address', 'address_line1')
    op.add_column('customers_address', sa.Column('address_line', sa.String(length=100), nullable=True))
    op.drop_column('customers_address', 'address_line_2')
    op.drop_column('customers_address', 'address_line_1')
    op.add_column('vendors_address', sa.Column('address_line', sa.String(length=100), nullable=True))
    op.drop_column('vendors_address', 'address_line_2')
    op.drop_column('vendors_address', 'address_line_1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors_address', sa.Column('address_line_1', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('vendors_address', sa.Column('address_line_2', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('vendors_address', 'address_line')
    op.add_column('customers_address', sa.Column('address_line_1', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('customers_address', sa.Column('address_line_2', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('customers_address', 'address_line')
    op.add_column('address', sa.Column('address_line1', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('address', sa.Column('address_line2', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('address', 'address_line')
    # ### end Alembic commands ###
