"""empty message

Revision ID: f58beb923996
Revises: f7696a012821
Create Date: 2020-07-16 16:27:06.359256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58beb923996'
down_revision = 'f7696a012821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_product_features_extra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('product_varient_id', sa.Integer(), nullable=True),
    sa.Column('feature_type_id', sa.Integer(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_varient_id'], ['global_product_products_varient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_product_features_double_recommended',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_value', sa.Float(), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['global_product_category_feature.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_product_features_integer_recommended',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_value', sa.Integer(), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['global_product_category_feature.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_product_features_string_recommended',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_value', sa.String(length=1000), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['global_product_category_feature.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_product_features_recommended',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.Column('product_varient_id', sa.Integer(), nullable=True),
    sa.Column('string_seleted_id', sa.Integer(), nullable=True),
    sa.Column('integer_seleted_id', sa.Integer(), nullable=True),
    sa.Column('double_seleted_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['double_seleted_id'], ['global_product_features_double_recommended.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['global_product_category_feature.id'], ),
    sa.ForeignKeyConstraint(['integer_seleted_id'], ['global_product_features_integer_recommended.id'], ),
    sa.ForeignKeyConstraint(['product_varient_id'], ['global_product_products_varient.id'], ),
    sa.ForeignKeyConstraint(['string_seleted_id'], ['global_product_features_string_recommended.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_product_features_recommended')
    op.drop_table('global_product_features_string_recommended')
    op.drop_table('global_product_features_integer_recommended')
    op.drop_table('global_product_features_double_recommended')
    op.drop_table('global_product_features_extra')
    # ### end Alembic commands ###
