"""empty message

Revision ID: f75f95b0e2b3
Revises: 58efac41c066
Create Date: 2020-07-20 12:22:48.451293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f75f95b0e2b3'
down_revision = '58efac41c066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_product_products_varient', sa.Column('master_product', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_product_products_varient', 'master_product')
    # ### end Alembic commands ###
