"""empty message

Revision ID: 0dc580d98211
Revises: 6562a4601a2b
Create Date: 2020-05-24 16:40:58.803297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc580d98211'
down_revision = '6562a4601a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'created_at')
    # ### end Alembic commands ###
