"""empty message

Revision ID: 1ac4186493dd
Revises: 7bb68cecd174
Create Date: 2020-05-25 17:00:54.213048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ac4186493dd'
down_revision = '7bb68cecd174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features__datatype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('features__data_type')
    op.add_column('sub__category__feature', sa.Column('features_datatype_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sub__category__feature', 'features__datatype', ['features_datatype_id'], ['id'])
    op.drop_column('sub__category__feature', 'feature_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub__category__feature', sa.Column('feature_type', mysql.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'sub__category__feature', type_='foreignkey')
    op.drop_column('sub__category__feature', 'features_datatype_id')
    op.create_table('features__data_type',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('features__datatype')
    # ### end Alembic commands ###
