"""empty message

Revision ID: 33158a16c3a0
Revises: ba474f156896
Create Date: 2020-06-02 19:16:51.583524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33158a16c3a0'
down_revision = 'ba474f156896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category__feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.Column('features_datatype_id', sa.Integer(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['features_datatype_id'], ['features__datatype.id'], ),
    sa.ForeignKeyConstraint(['sub_category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sub__category__feature')
    op.drop_table('sub__category')
    op.drop_constraint('boolean__features_ibfk_1', 'boolean__features', type_='foreignkey')
    op.create_foreign_key(None, 'boolean__features', 'category__feature', ['feature_id'], ['id'])
    op.drop_constraint('date__features_ibfk_1', 'date__features', type_='foreignkey')
    op.create_foreign_key(None, 'date__features', 'category__feature', ['feature_id'], ['id'])
    op.drop_constraint('double__features_ibfk_1', 'double__features', type_='foreignkey')
    op.create_foreign_key(None, 'double__features', 'category__feature', ['feature_id'], ['id'])
    op.drop_constraint('integer__features_ibfk_1', 'integer__features', type_='foreignkey')
    op.create_foreign_key(None, 'integer__features', 'category__feature', ['feature_id'], ['id'])
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint('products_ibfk_1', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'category', ['category_id'], ['id'])
    op.drop_column('products', 'sub_category_id')
    op.drop_constraint('string__features_ibfk_1', 'string__features', type_='foreignkey')
    op.create_foreign_key(None, 'string__features', 'category__feature', ['feature_id'], ['id'])
    op.add_column('varient', sa.Column('category_feature_id', sa.Integer(), nullable=True))
    op.drop_constraint('varient_ibfk_2', 'varient', type_='foreignkey')
    op.create_foreign_key(None, 'varient', 'category__feature', ['category_feature_id'], ['id'])
    op.drop_column('varient', 'sub_category_feature_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('varient', sa.Column('sub_category_feature_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'varient', type_='foreignkey')
    op.create_foreign_key('varient_ibfk_2', 'varient', 'sub__category__feature', ['sub_category_feature_id'], ['id'])
    op.drop_column('varient', 'category_feature_id')
    op.drop_constraint(None, 'string__features', type_='foreignkey')
    op.create_foreign_key('string__features_ibfk_1', 'string__features', 'sub__category__feature', ['feature_id'], ['id'])
    op.add_column('products', sa.Column('sub_category_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_ibfk_1', 'products', 'sub__category', ['sub_category_id'], ['id'])
    op.drop_column('products', 'category_id')
    op.drop_constraint(None, 'integer__features', type_='foreignkey')
    op.create_foreign_key('integer__features_ibfk_1', 'integer__features', 'sub__category__feature', ['feature_id'], ['id'])
    op.drop_constraint(None, 'double__features', type_='foreignkey')
    op.create_foreign_key('double__features_ibfk_1', 'double__features', 'sub__category__feature', ['feature_id'], ['id'])
    op.drop_constraint(None, 'date__features', type_='foreignkey')
    op.create_foreign_key('date__features_ibfk_1', 'date__features', 'sub__category__feature', ['feature_id'], ['id'])
    op.drop_constraint(None, 'boolean__features', type_='foreignkey')
    op.create_foreign_key('boolean__features_ibfk_1', 'boolean__features', 'sub__category__feature', ['feature_id'], ['id'])
    op.create_table('sub__category',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='sub__category_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sub__category__feature',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('sub_category_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('units', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('features_datatype_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['features_datatype_id'], ['features__datatype.id'], name='sub__category__feature_ibfk_2'),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub__category.id'], name='sub__category__feature_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('category__feature')
    # ### end Alembic commands ###
