"""empty message

Revision ID: aa504ad5f9ca
Revises: 1ac4186493dd
Create Date: 2020-05-26 17:05:25.445236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa504ad5f9ca'
down_revision = '1ac4186493dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extra__features', sa.Column('feature_type_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extra__features', 'feature_type_id')
    # ### end Alembic commands ###
