"""empty message

Revision ID: ba474f156896
Revises: aa504ad5f9ca
Create Date: 2020-05-26 17:46:27.013176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba474f156896'
down_revision = 'aa504ad5f9ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('varient', sa.Column('sub_category_feature_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'varient', 'sub__category__feature', ['sub_category_feature_id'], ['id'])
    op.drop_column('varient', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('varient', sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'varient', type_='foreignkey')
    op.drop_column('varient', 'sub_category_feature_id')
    # ### end Alembic commands ###
